server:
  port: 8090

spring:
  datasource:
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ProductDB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#Jwt


secretkey: ${secretkey}
audience:  ${audience}
issuer:    ${issuer}

myapplication:
  feign:
    stock: http://localhost:8092/api/v1